// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignWorkspace(arg1, arg2) {
  return window['go']['main']['App']['AssignWorkspace'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function RunFix(arg1) {
  return window['go']['main']['App']['RunFix'](arg1);
}

export function ScanConversations() {
  return window['go']['main']['App']['ScanConversations']();
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}
