// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {main} from '../models';

export function AssignWorkspace(arg1:string,arg2:string):Promise<boolean>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function RunFix(arg1:main.FixOptions):Promise<main.FixResult>;

export function ScanConversations():Promise<main.ScanResult>;

export function SelectFolder(arg1:string):Promise<string>;
